const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Product = require('./models/productModel');
const User = require('./models/userModel');

const products = [
  // ─── LUXURY WATCHES ───────────────────────────────────────
  {
    name: 'Chronos Imperial Gold',
    description: 'Swiss-engineered automatic movement encased in 18k brushed gold. Sapphire crystal glass, exhibition caseback, and alligator leather strap. Water resistant to 100m. A masterpiece of horological engineering.',
    price: 4200,
    category: 'Luxury Watches',
    colors: ['Gold', 'Black'],
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=90',
    countInStock: 8,
    featured: true,
    rating: 4.9,
    numReviews: 24,
  },
  {
    name: 'Noir Phantom Chronograph',
    description: 'All-black PVD-coated stainless steel case with ceramic bezel. Tri-colour subdials on sunburst matte dial. 48-hour power reserve, 300m water resistance. The ultimate statement in avant-garde watchmaking.',
    price: 5800,
    category: 'Luxury Watches',
    colors: ['Black', 'Silver'],
    image: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&q=90',
    countInStock: 5,
    featured: true,
    rating: 4.8,
    numReviews: 18,
  },
  {
    name: 'Rose Pavillon Tourbillon',
    description: 'Flying tourbillon movement visible through the open-worked dial. Rose gold case with hand-engraved floral motifs. Hand-stitched ostrich leather strap with butterfly deployment clasp. Limited to 50 pieces worldwide.',
    price: 18500,
    category: 'Luxury Watches',
    colors: ['Rose Gold'],
    image: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800&q=90',
    countInStock: 3,
    featured: true,
    rating: 5.0,
    numReviews: 7,
  },
  {
    name: 'Aqua Sovereign Diver',
    description: 'Professional diving watch with unidirectional ceramic bezel. Helium escape valve, luminescent hands, and 600m water resistance. Grade 5 titanium case for exceptional strength with minimal weight.',
    price: 3600,
    category: 'Luxury Watches',
    colors: ['Blue', 'Silver'],
    image: 'https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=800&q=90',
    countInStock: 12,
    featured: false,
    rating: 4.7,
    numReviews: 31,
  },
  {
    name: 'Celestia Moonphase',
    description: 'Elegant dress watch featuring a poetic moonphase complication. Mother-of-pearl dial with diamond hour markers. Ultra-thin 7mm profile. White gold case on a navy blue hand-sewn cordovan strap.',
    price: 7200,
    category: 'Luxury Watches',
    colors: ['White Gold', 'Blue'],
    image: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&q=90',
    countInStock: 6,
    featured: false,
    rating: 4.9,
    numReviews: 14,
  },
  {
    name: 'Prestige GMT Explorer',
    description: 'Dual timezone functionality in a sporty yet elegant package. Stainless steel Oyster case with scratch-resistant ceramic bezel insert. Jubilee bracelet with fine-adjustment clasp. Perfect for the global traveller.',
    price: 6100,
    category: 'Luxury Watches',
    colors: ['Silver', 'Black', 'Blue'],
    image: 'https://images.unsplash.com/photo-1639891683651-0f9c2a06f1cb?w=800&q=90',
    countInStock: 9,
    featured: false,
    rating: 4.6,
    numReviews: 22,
  },
  // ─── DESIGNER BAGS ────────────────────────────────────────
  {
    name: 'Heritage Grand Tote',
    description: 'Full-grain vegetable-tanned Italian leather. Reinforced base, polished brass hardware, and a detachable suede pouch. Roomy interior with zip pocket and pen slots. Ages magnificently to a rich patina.',
    price: 1850,
    category: 'Designer Bags',
    colors: ['Cognac', 'Black', 'Burgundy'],
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=90',
    countInStock: 14,
    featured: true,
    rating: 4.9,
    numReviews: 38,
  },
  {
    name: 'Obsidian Quilted Clutch',
    description: 'Iconic diamond-quilted lambskin leather with gold chain strap. Magnetic snap closure with satin-lined interior. Compact yet capacious enough for your evening essentials. Handmade in Florence, Italy.',
    price: 2200,
    category: 'Designer Bags',
    colors: ['Black', 'Ivory', 'Gold'],
    image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=90',
    countInStock: 10,
    featured: true,
    rating: 4.8,
    numReviews: 27,
  },
  {
    name: 'Verdana Structured Satchel',
    description: 'Box-shaped satchel in pebbled calfskin. Signature Aurelia Luxe engraved lock clasp. Padded laptop sleeve, external zip pocket, and convertible shoulder strap. The power bag for the modern executive.',
    price: 3100,
    category: 'Designer Bags',
    colors: ['Forest Green', 'Camel', 'Black'],
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=800&q=90',
    countInStock: 7,
    featured: false,
    rating: 4.7,
    numReviews: 19,
  },
  {
    name: 'Luna Crescent Shoulder Bag',
    description: 'Crescent-shaped silhouette in butter-soft nappa leather. Single adjustable strap with 14k gold-plated hardware. Suede interior with mirror pouch. A sculptural statement for the discerning collector.',
    price: 1650,
    category: 'Designer Bags',
    colors: ['Cream', 'Taupe', 'Blush'],
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=90',
    countInStock: 11,
    featured: false,
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: 'Midas Mini Crossbody',
    description: 'Miniature crossbody in python-embossed leather with 24k gold chain. Interior divided into card slots, a phone pocket, and a zip coin purse. The perfect companion for evenings and weekends alike.',
    price: 980,
    category: 'Designer Bags',
    colors: ['Gold', 'Black', 'Cognac'],
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=90',
    countInStock: 18,
    featured: false,
    rating: 4.5,
    numReviews: 42,
  },
  {
    name: 'Riviera Woven Basket Tote',
    description: 'Summer luxury redefined. Hand-woven raffia body with full-grain leather handles and base. Canvas-lined interior with zip closure. Packable yet infinitely chic. From beach to bistro.',
    price: 760,
    category: 'Designer Bags',
    colors: ['Natural', 'Black'],
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=90',
    countInStock: 20,
    featured: false,
    rating: 4.4,
    numReviews: 33,
  },
  // ─── PREMIUM SHOES ────────────────────────────────────────
  {
    name: 'Aria White Leather Sneakers',
    description: 'Handcrafted in our Milanese atelier from full-grain calfskin leather. Cushioned orthopaedic insole with memory foam. Margom rubber sole for superior grip. A modern classic that transcends trends.',
    price: 680,
    category: 'Premium Shoes',
    colors: ['White', 'Cream'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=90',
    countInStock: 22,
    featured: true,
    rating: 4.8,
    numReviews: 56,
  },
  {
    name: 'Venetian Oxford Brogues',
    description: 'Classic brogue detailing on a Blake-stitched construction. Burnished calf leather with hand-finished edges. Full leather lining and leather outsole with rubber heel insert. Goodyear welted for resolability.',
    price: 1100,
    category: 'Premium Shoes',
    colors: ['Dark Brown', 'Black', 'Tan'],
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=90',
    countInStock: 16,
    featured: true,
    rating: 4.9,
    numReviews: 29,
  },
  {
    name: 'Noir Running Pro Elite',
    description: 'Performance meets luxury. Knit upper with precision zones of support and flexibility. Full-length carbon fibre plate for propulsive energy return. Exclusive Aurelia Luxe edition with embossed gold branding.',
    price: 490,
    category: 'Premium Shoes',
    colors: ['Black', 'White', 'Navy'],
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=90',
    countInStock: 30,
    featured: false,
    rating: 4.7,
    numReviews: 74,
  },
  {
    name: 'Chelsea Heritage Boots',
    description: 'Pull-on Chelsea silhouette in waxed suede. Elasticated ankle gussets and leather loop. Leather-lined, rubber-soled for urban terrain. A perennial wardrobe cornerstone, elevated.',
    price: 820,
    category: 'Premium Shoes',
    colors: ['Tan', 'Black', 'Charcoal'],
    image: 'https://images.unsplash.com/photo-1638953285032-a501f3a99fd1?w=800&q=90',
    countInStock: 13,
    featured: false,
    rating: 4.6,
    numReviews: 21,
  },
  {
    name: 'Stiletto Crystal Mule',
    description: 'Transparent PVC upper adorned with Swarovski crystals. 105mm stiletto heel in lacquered gold. Leather insole and padded footbed. Handmade in Spain. The ultimate luxury heel for extraordinary moments.',
    price: 1350,
    category: 'Premium Shoes',
    colors: ['Crystal', 'Black Crystal'],
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=90',
    countInStock: 6,
    featured: true,
    rating: 4.9,
    numReviews: 11,
  },
  {
    name: 'Loafer Penny Monk Strap',
    description: 'Double monk strap loafer in polished box calf leather. Gold-plated buckles and a hand-stitched apron toe. Handmade in Northampton, England using 200-year-old techniques. The pinnacle of English shoemaking.',
    price: 940,
    category: 'Premium Shoes',
    colors: ['Mahogany', 'Black'],
    image: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800&q=90',
    countInStock: 9,
    featured: false,
    rating: 4.8,
    numReviews: 17,
  },
  // ─── EXCLUSIVE APPAREL ────────────────────────────────────
  {
    name: 'Cashmere Cloud Crewneck',
    description: 'Spun from Grade-A Mongolian cashmere at 2-ply weight. Garment-washed for an incredibly soft hand feel. Dropped shoulders, ribbed cuffs and hem. Available in a curated palette of 12 refined tones.',
    price: 620,
    category: 'Exclusive Apparel',
    colors: ['Oatmeal', 'Camel', 'Slate', 'Navy', 'Ivory'],
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=90',
    countInStock: 25,
    featured: true,
    rating: 4.9,
    numReviews: 48,
  },
  {
    name: 'Silk Fluid Blazer',
    description: '100% mulberry silk crepe de chine. Unstructured, fluid silhouette with padded shoulders. Horn buttons and hand-finished buttonholes. Fully silk-lined. Dry clean only. Designed in Paris, made in Italy.',
    price: 1480,
    category: 'Exclusive Apparel',
    colors: ['Champagne', 'Midnight', 'Blush'],
    image: 'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=90',
    countInStock: 8,
    featured: true,
    rating: 4.8,
    numReviews: 23,
  },
  {
    name: 'Linen Palazzo Trousers',
    description: 'Wide-leg palazzo trousers in deadstock Irish linen. High-rise waist with invisible side zip. Pressed centre crease. Unlined for breathability. The effortless luxury of summer dressing.',
    price: 380,
    category: 'Exclusive Apparel',
    colors: ['Sand', 'White', 'Sage', 'Black'],
    image: 'https://images.unsplash.com/photo-1594938374182-a57369e3a1c5?w=800&q=90',
    countInStock: 19,
    featured: false,
    rating: 4.5,
    numReviews: 36,
  },
  {
    name: 'Tuxedo Dinner Jacket',
    description: 'Peak-lapel tuxedo in Super 180s wool. Satin lapels and piping. Hand-padded chest and basted seams. Two-button sleeve with functioning buttonholes. Fully canvassed construction. Made-to-measure options available.',
    price: 2800,
    category: 'Exclusive Apparel',
    colors: ['Midnight Black', 'Ivory'],
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=90',
    countInStock: 5,
    featured: true,
    rating: 5.0,
    numReviews: 9,
  },
  {
    name: 'Wrap Silk Midi Dress',
    description: 'Bias-cut wrap dress in hand-printed silk charmeuse. Adjustable tie waist, V-neckline, and flutter sleeves. Fully lined. Each piece features a unique hand-painted motif by our in-house artists.',
    price: 1100,
    category: 'Exclusive Apparel',
    colors: ['Floral Ivory', 'Geometric Navy', 'Abstract Blush'],
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=90',
    countInStock: 10,
    featured: false,
    rating: 4.7,
    numReviews: 28,
  },
  {
    name: 'Merino Turtleneck',
    description: 'Extra-fine Merino wool in a snug ribbed turtleneck silhouette. 18.5-micron fibre for next-to-skin comfort. Machine washable at 30°C. The everyday luxury essential that anchors any wardrobe.',
    price: 290,
    category: 'Exclusive Apparel',
    colors: ['Espresso', 'Cream', 'Forest', 'Bordeaux'],
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=90',
    countInStock: 32,
    featured: false,
    rating: 4.6,
    numReviews: 51,
  },
  {
    name: 'Tailored Houndstooth Coat',
    description: 'Classic houndstooth pattern in a premium wool-cashmere blend. Double-breasted, notched lapel construction. Hand-stitched welt pockets and full satin lining. The quintessential investment piece.',
    price: 2200,
    category: 'Exclusive Apparel',
    colors: ['Black/White', 'Camel/Brown'],
    image: 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=800&q=90',
    countInStock: 7,
    featured: false,
    rating: 4.8,
    numReviews: 16,
  },
  {
    name: 'Leather Moto Jacket',
    description: 'Perfecto-style biker jacket in vegetable-tanned lamb nappa leather. YKK zippers throughout, quilted elbow panels, and silver-tone hardware. Fully viscose-lined. Gets better with every wear.',
    price: 1750,
    category: 'Exclusive Apparel',
    colors: ['Black', 'Bordeaux', 'Dark Olive'],
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=90',
    countInStock: 11,
    featured: true,
    rating: 4.9,
    numReviews: 34,
  },
  {
    name: 'Broderie Anglaise Blouse',
    description: 'Romantic broderie anglaise in 100% cotton voile. Puffed sleeves with gathered cuffs, a button-through front, and an open collar. Partially lined. Hand-embroidered accents at the hem.',
    price: 320,
    category: 'Exclusive Apparel',
    colors: ['White', 'Ecru', 'Powder Blue'],
    image: 'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=800&q=90',
    countInStock: 24,
    featured: false,
    rating: 4.4,
    numReviews: 19,
  },
  {
    name: 'Heritage Wool Kilt Skirt',
    description: "Tartan kilt skirt woven on traditional Scottish looms. Pure new wool in Aurelia Luxe's exclusive tartan. Safety-pin fastening and leather strap buckle. Knee-length with box pleats at the rear.",
    price: 560,
    category: 'Exclusive Apparel',
    colors: ['Classic Tartan', 'Navy Tartan', 'Earth Tartan'],
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&q=90',
    countInStock: 15,
    featured: false,
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: 'Crystal Embellished Gown',
    description: 'Floor-length column gown in stretch crepe with 3,500 hand-applied Swarovski crystals. Built-in boning and corseted waist. Sweep train. A couture masterpiece for the most significant occasions.',
    price: 5600,
    category: 'Exclusive Apparel',
    colors: ['Midnight', 'Champagne', 'Ivory'],
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=90',
    countInStock: 3,
    featured: true,
    rating: 5.0,
    numReviews: 6,
  },
  {
    name: 'Pima Cotton Dress Shirt',
    description: '200-thread-count two-ply Peruvian Pima cotton. Spread collar, mother-of-pearl buttons, and a slim placket. Hand-finished buttonholes and split back yoke. The foundation of a luxurious wardrobe.',
    price: 195,
    category: 'Exclusive Apparel',
    colors: ['White', 'Sky Blue', 'Pale Pink', 'Ecru'],
    image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800&q=90',
    countInStock: 40,
    featured: false,
    rating: 4.7,
    numReviews: 62,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected for seeding...');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Products cleared.');

    // Get or create an admin user to be the seller
    let admin = await User.findOne({ role: 'admin' });
    if (!admin) {
      admin = await User.create({
        name: 'Manish Kumar',
        email: 'admin@aurelia.com',
        password: 'admin123456',
        role: 'admin',
      });
      console.log('Admin user created: admin@aurelia.com / admin123456');
    }

    // Attach seller id to all products
    const productsWithSeller = products.map((p) => ({ ...p, seller: admin._id }));
    await Product.insertMany(productsWithSeller);
    console.log(`✅ ${products.length} products seeded successfully!`);
    console.log('\n─────────────────────────────────────');
    console.log('Admin Login → admin@aurelia.com');
    console.log('Password   → admin123456');
    console.log('─────────────────────────────────────\n');

    process.exit(0);
  } catch (error) {
    console.error('Seeder Error:', error);
    process.exit(1);
  }
};

seedDB();
